version: '2'
services:

  php:
    build: ./docker/php/
    depends_on:
      - db
    ports:
      - "${PHP_EXTERNAL_PORT}:9000"
    volumes:
      - ".:/var/www/html"
    command: "php -S 0.0.0.0:9000 -t /var/www/html/public /var/www/html/public/index.php"

  db:
    image: postgres:9.5
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - "${DB_EXTERNAL_VOLUME}:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  swagger_ui:
    image: sjeandeaux/docker-swagger-ui
    depends_on:
      - php
    ports:
      - "${SWAGGER_UI_EXTERNAL_PORT}:8888"
    environment:
      API_URL: ${SWAGGER_UI_API_URL}

  swagger_editor:
    image: sjeandeaux/docker-swagger-editor
    ports:
      - "${SWAGGER_EDITOR_EXTERNAL_PORT}:8888"