version: '2'
services:

  nginx:
    build: ./docker/nginx/
    depends_on:
      - php
      - swagger_ui
      - swagger_editor
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    volumes:
      - ".:/var/www/html"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"

  php:
    build: ./docker/php/
    depends_on:
      - db
    volumes:
      - ".:/var/www/html"
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}

  db:
    image: postgres:9.5
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - "${DB_EXTERNAL_VOLUME}:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  swagger_ui:
    image: sjeandeaux/docker-swagger-ui
    depends_on:
      - php
    environment:
      API_URL: ${SWAGGER_UI_API_URL}

  swagger_editor:
    image: sjeandeaux/docker-swagger-editor