version: '2'
services:

  db:
    image: postgres:9.5
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - "${DB_EXTERNAL_VOLUME}:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}